# Note that gcc is the GNU Compiler Collection and
# g++ is the compiler driver (for c++) [whatever that means]
# The -g flag sets the gdb flag
# The -std flag sets the c++ standard to be C++11
# The -o specifies the output file name after compilation

stack:
	g++ -std=c++11 -o bagtest bagtest.cc
clean:
	rm bagtest
